services:
  wp:
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - 5010:80
    volumes:
      - conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - html:/var/www/html # Full wordpress project
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - wp-db
  wp-db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
  pma:
    image: phpmyadmin:latest
    ports:
      - 5011:80
    volumes:
      - pma_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - pma_config.php:/etc/phpmyadmin/config.user.inc.php
    restart: unless-stopped
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: wp-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
    depends_on:
      - wp-db
  wp-db-backup:
#    container_name: wp-db-backup
    image: tiredofit/db-backup
    volumes:
      - backups:/backup
    restart: unless-stopped
    environment:
      DB_TYPE: mysql
      DB_HOST: wp-db
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASSWORD}"
      DB_BACKUP_INTERVAL: 720
      DB_CLEANUP_TIME: 72000
      #DB_BACKUP_BEGIN: 1
      CHECKSUM: SHA1
      COMPRESSION: GZ
      CONTAINER_ENABLE_MONITORING: "false"
    depends_on:
      - wp-db
volumes:
  conf.ini:
  html:
  mysql_data:
  pma_php.ini:
  pma_config.php:
  backups:
